events {}

http {
  server {
    listen 80;

    location /cloudfront {
      rewrite ^/cloudfront/(.*) /$1 break;
      proxy_pass ${MINIO_ENDPOINT};
      proxy_cache cloudfront_cache;
      proxy_cache_valid 200 1m;
      proxy_cache_use_stale error timeout updating;
    }
  }

  proxy_cache_path /tmp/cloudfront_cache levels=1:2 keys_zone=cloudfront_cache:10m inactive=60m;
}
