import { extendTailwindMerge } from 'tailwind-merge';

export const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': [
        'text-heading-large',
        'text-heading-medium',
        'text-heading-small',
        'text-quote-large',
        'text-quote-medium',
        'text-paragraph-large',
        'text-paragraph-medium',
        'text-paragraph-small',
        'text-paragraph-caption',
        'text-paragraph-caption-small',
      ],
      'font-family': [
        'font-dm-sans-regular',
        'font-dm-sans-italic',
        'font-dm-sans-medium',
        'font-dm-sans-medium-italic',
        'font-dm-sans-semi-bold',
        'font-dm-sans-semi-bold-italic',
        'font-dm-sans-bold',
        'font-dm-sans-bold-italic',
        'font-playfair-regular',
        'font-playfair-italic',
        'font-playfair-medium',
        'font-playfair-medium-italic',
        'font-playfair-semi-bold',
        'font-playfair-semi-bold-italic',
        'font-playfair-bold',
        'font-playfair-bold-italic',
      ],
      shadow: ['custom'],
    },
    theme: {
      color: [
        'primary',
        'primary-foreground',
        'secondary',
        'secondary-foreground',
        'background',
        'foreground',
        'card',
        'muted',
        'muted-foreground',
        'border',
        'input',
        'destructive',
        'destructive-foreground',
        'success',
        'success-foreground',
        'accent',
        'accent-foreground',
      ],
    },
  },
});
