import { vars } from 'nativewind';

export const themes = {
  light: vars({
    '--theme-primary': '#074C4E',
    '--theme-primary-contrast': '#FFFFFF',
    '--theme-button-primary': '#074C4E',
    '--theme-background': '#FFFFFF',
    '--theme-background-contrast': '#000000',
    '--theme-error': '#EA3838',
    '--theme-error-light': '#FBECEC',
    '--theme-success': '#4ABC86',
    '--theme-success-light': '#D8FFEC',
    '--theme-market': '#F86F2D',
    '--theme-paragraph': '#636363',
    '--theme-paragraph-secondary': '#636363',
    '--theme-icon-color': '#074C4E',
    '--theme-icon-fill-color': '#FFFFFF',
    '--theme-on-background-gray-1': '#636363',
    '--theme-on-background-gray-2': '#E1E1E1',
  }),
  dark: vars({
    '--theme-primary': '#074C4E',
    '--theme-primary-contrast': '#FFFFFF',
    '--theme-button-primary': '#074C4E',
    '--theme-background': '#000000',
    '--theme-background-contrast': '#FFFFFF',
    '--theme-error': '#EA3838',
    '--theme-error-light': '#FBECEC',
    '--theme-success': '#4ABC86',
    '--theme-success-light': '#D8FFEC',
    '--theme-market': '#F86F2D',
    '--theme-paragraph': '#636363',
    '--theme-paragraph-secondary': '#636363',
    '--theme-icon-color': '#074C4E',
    '--theme-icon-fill-color': '#FFFFFF',
    '--theme-on-background-gray-1': '#636363',
    '--theme-on-background-gray-2': '#E1E1E1',
  }),
};
