export const lightThemeColors = {
  primary: '#B5845A',
  primaryForeground: '#ffffff',
  background: '#F8F6F0',
  foreground: '#2D2D28',
  muted: '#E8E4DC',
  mutedForeground: '#9B8E7E',
  border: '#D9CEBC',
  input: '#D9CEBC',
  destructive: '#C45D4A',
  destructiveForeground: '#ffffff',
  success: '#7A8B6F',
  successForeground: '#ffffff',
  accent: '#7A8B6F',
  accentForeground: '#ffffff',
  card: '#FFFFFF',
  secondary: '#7A8B6F',
  secondaryForeground: '#ffffff',
};

export const darkThemeColors: typeof lightThemeColors = {
  primary: '#C49468',
  primaryForeground: '#1A1B18',
  background: '#1A1B18',
  foreground: '#F0EDE5',
  muted: '#2A2B26',
  mutedForeground: '#8A8478',
  border: '#3A3B35',
  input: '#3A3B35',
  destructive: '#D4634F',
  destructiveForeground: '#ffffff',
  success: '#8B9B7F',
  successForeground: '#ffffff',
  accent: '#8B9B7F',
  accentForeground: '#ffffff',
  card: '#232420',
  secondary: '#8B9B7F',
  secondaryForeground: '#ffffff',
};

export type ThemeColors = typeof lightThemeColors;
